# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
  - stage: Build
    jobs:
      - job: macOS
        pool:
          vmImage: 'macOS-10.13'
        strategy:
          matrix:
            node_4_x:
              node_version: 4.x
            node_5_x:
              node_version: 5.x
            node_6_13_x:
              node_version: 6.13.x
            node_7_x:
              node_version: 7.x
            node_8_10_x:
              node_version: 8.10.x
            node_9_10_x:
              node_version: 9.10.x
        steps:
          - checkout: self
            clean: true
            submodules: recursive
          - task: NodeTool@0
            inputs:
              versionSpec: $(node_version)
          - script: npm install # this will build the bindings
            workingDirectory: nan
          - script: node test.js
            workingDirectory: nan

            